#!/bin/bash


set -e


NAME=tomato
PIDFILE=/var/run/$NAME.pid
DAEMON=/bin/start_tomato.sh
case "$1" in
        start)
            echo -n "Starting daemon: "$NAME
            start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON
            echo "."
            ;;
        stop)
            echo -n "Stopping daemon: "$NAME
            start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
            echo "."
            ;;
        restart)
            echo -n "Restarting daemon: "$NAME
            start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
            start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON
            echo "."
            ;;
        *)
            echo "Usage: "$1" {start|stop|restart}"
            exit 1
esac
exit 0
